kind: Service
apiVersion: v1
metadata:
  name:  backend-clusterip
  labels:
    name: backend-app
    tier: backend
spec:
  selector:
    app:  backend-app
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort:  8080