apiVersion: apps/v1
kind: Deployment
medadata: 
  name: my-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: my-app-deployment
  template:
    metadata:
      name: my-app-pod
      labels:
        name:  my-deployment
    spec:
      containers:
        - name: my-app-container
          image: ubuntu
          ports:
          - containerPort: 80