apiVersion: v1
kind: Service
metadata:
  name: my-deployment-nodeport
spec:
  selector:
    app: my-app-deployment
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31234