kind: Service
apiVersion: v1
metadata:
  name:  frontend-app-nodeport
  labels:
    name: frontend-app
    tier: frontend
spec:
  selector:
    app:  frontend-app
  type:  NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80
    nodePort: 31235