apiVersion: v1
kind: Namespace
metadata:
  name: dev1

--- 

apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
  namespace: dev1
spec:
  limits: 
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      type: Container

--- 

apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-resource-quota
  namespace: dev1
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "5"
    persistentVolumeClaim: "5"
    configmap: "5"
    secrets: "5"
    services: "5"