apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: dev1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Receate    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysqlimage
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: db-password
        ports:
        - name:  mysql
          containerPort: 3306
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: var/lib/mysql
          - name: usermgmt-database-creation-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-mysql-pvc
        - name: usermgmt-database-creation-script
          configMap:
            name: mysql-configmap