apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-microservice-deployment-v2
  labels:
    name: notification-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        name: notification-restapp
    spec:
      containers:
      - image: kube-notifications-microservice:4.0.0-AWS-XRay
        name: notification-service     
        ports:
        - containerPort: 8096
      restartPolicy: Always
      imagePullPolicy: Always
      env:
        - name: AWS_MAIL_SERVER_HOST
          value: "smtp-service"
        - name: AWS_MAIL_SERVER_FROM_ADDRESS
          value: "vibhurawat47@gmail.com" 
        - name: AWS_MAIL_SERVER_USERNAME
          value: "AKIASUF7HC7SQJ6BCLVS"
        - name: AWS_MAIL_SERVER_PASSWORD
          value: "BARcmLiC68wgmhTy/cQvz/E8vFzeizGqdeASNtCs6+Nv"   