apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usermgmt-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:
    metadata:
      labels:
        app: usermgmt-restapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.3
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
      - name: usermgmt-restapp-container
        image: kube-usermanagement-microservice:3.0.0-AWS-XRay-MySQLDB
        ports:
          - containerPort: 8095 
        env:
          - name: DB_HOSTNAME
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: usermgmt
          - name: DB_USERNAME
            value: "dbadmin" 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: db-password
          - name: NOTIFICATION_SERVICE_HOST
            value: "notification-clusterip-service"
          - name: NOTIFICATION_SERVICE_PORT
            value: "8096" 
          - name: AWS_XRAY_TRACING_NAME 
            value: "User-Management-Microservice"                
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: "xray-service.default:2000"    
          - name: AWS_XRAY_CONTEXT_MISSING 
            value: "LOG_ERROR"                   
        livenessProbe:
          exec:
            command:
              - '/bin/bash'
              - '-c' 
              - 'nc -z localhost 8095'
          initialDelaySeconds: 10   
        readinessProbe:
          httpGet:
            path: /usermgmt/health-status
            port: 8095
          initialDelaySeconds: 10